# This is a template for the secrets.toml file
# You'll need to fill this with your actual proxy information
# when deploying to Streamlit Cloud

[proxy]
# Example format:
# PROXY_URL = "http://username:password@proxyserver:port"
PROXY_URL = "http://vpn:vpn@public-vpn-57.opengw.net:80"